#!/usr/bin/env bash

if [ $# != 1 ]; then
  echo "No filename specified";
  exit 1;
fi

filename="$1"
if [ ! -e "$filename.rs" ]; then
  echo "File '$filename.rs' does not exist";
  exit 1;
fi

rustc "$filename.rs" && ./$filename
if [ -e "$filename" ]; then
  rm "$filename"
fi