#!/usr/bin/env bash

if [ $# == 0 ]; then
  echo "No filename specified";
  exit 1;
fi

filename=$1
if [ ! -e "$filename.cpp" ]; then
  echo "File $filename.cpp does not exist";
  exit 1;
fi

g++ $filename.cpp -o $filename -std=c++20;
if [ -e $filename ]; then
  ./$filename;
  rm $filename;
fi
